// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire/internal/conf"
	"wire/internal/controller/controller_user"
	"wire/internal/repo/repo_user"
	"wire/internal/service/service_user"
)

// Injectors from wire.go:

//go:generate wire
func WireApp() (*conf.HttpServer, error) {
	sugaredLogger := conf.InitZap()
	engine := conf.NewGin()
	db := conf.InitDB()
	userRepo := &repo_user.UserRepo{
		DB: db,
	}
	userService := &service_user.UserService{
		UserRepo: userRepo,
	}
	userController := controller_user.NewUserController(engine, userService, sugaredLogger)
	httpServer := &conf.HttpServer{
		Logger:         sugaredLogger,
		Engine:         engine,
		UserController: userController,
	}
	return httpServer, nil
}
